---
- name: Install jenkins and tomcat for ci-cd setup
  hosts: devserver
  tasks:
   - name: Download and add the jenkins keys 
     shell: "{{item}}"
     with_items:
      - wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
      - echo deb https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list
   - name: Install jenkins
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: jenkins,b: no}
      - {a: git,b: no}
      - {a: maven,b: no}
- name: Install tomcat8 and tomcat8-admin on qa and prodservers
  hosts: servers
  tasks:
   - name: Install tomcat8 and tomcat8-admin
     apt:
      name: "{{item}}"
      state: present
      update_cache: no
     with_items:
      - tomcat8
      - tomcat8-admin
   - name: Copy tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat8


