---
- name: Install/uninstalling  s/w packages
  hosts: all
  tasks:
   - name: Install/uninstall s/w
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree,b: present,c: no}
      - {a: git,b: absent,c: no}
      - {a: apache2,b: latest,c: no}
      - {a: tomcat8,b: present,c: yes}
