---
- name: copy tomcat-users.xml
  copy:
   src: "{{file1}}"
   dest: "{{dest1}}"
- name: Change port of tomcat
  replace:
   regexp: "{{port1}}"
   replace: "{{port2}}"
   path: "{{path1}}"
  notify: Check url response
...

